### ISSUE TITLE
Error: Unexpected scalar {VARIABLE} at {VARIABLE}-{VARIABLE}

### ISSUE THREAD

**Issue by rickhernandezio** [jgranstrom/zipson#2]
I have a larger data set that I'm trying to uncompress and getting this error message.

Error: Unexpected scalar f at 11696307-11696343
    at Object.decompressScalar (/app/node_modules/zipson/lib/decompressor/scalar.js:98:11)
    at Object.decompressElement (/app/node_modules/zipson/lib/decompressor/element.js:15:32)
    at Object.decompressStages (/app/node_modules/zipson/lib/decompressor/stages.js:78:28)
    at Object.decompress (/app/node_modules/zipson/lib/decompress.js:32:14)
    at Object.parse (/app/node_modules/zipson/lib/index.js:16:25)
    at Response.<anonymous> (/app/build/app.js:3549:49)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

**Comment by rickhernandezio** [comment]
The error gets thrown here.

    let response = parse(data.Body.toString());

**Comment by rickhernandezio** [comment]
Looks like after some more debugging this error was because of the `\\` not being escaped in a string. I ended up just escaping them before they got encoded. It's not ideal but it works for my situation.
